//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB3_Register_Enums.h>

//-----------------------------------------------------------------------------
// Global Constants
//-----------------------------------------------------------------------------
// Configurator set for HFOSC0/8
#define SYSCLK             3062000

// Configurator set for timer overflow every 100 ms / 10 Hz.
#define LED_TOGGLE_RATE           100  // LED toggle rate in milliseconds
// if LED_TOGGLE_RATE = 1, the LED will
// be on for 1 millisecond and off for
// 1 millisecond

//-----------------------------------------------------------------------------
// Pin Declarations
//-----------------------------------------------------------------------------
SI_SBIT (LED_GREEN, SFR_P1, 4);// green LED
SI_SBIT (LED_BLUE, SFR_P1, 5);// blue LED
SI_SBIT(LED_RED, SFR_P1, 6);// red LED

//-----------------------------------------------------------------------------
// INT0_ISR
//-----------------------------------------------------------------------------
//
// INT0 ISR Content goes here. Remember to clear flag bits:
// TCON::IE0 (External Interrupt 0)
//
// Whenever a negative edge appears on P0.2, toggle LED_GREEN.
// The interrupt pending flag is automatically cleared by vectoring to the ISR
//
//-----------------------------------------------------------------------------
/*SI_INTERRUPT (INT0_ISR, INT0_IRQn)
{
	LED_GREEN = !LED_GREEN;
}*/

//-----------------------------------------------------------------------------
// INT1_ISR
//-----------------------------------------------------------------------------
//
// INT1 ISR Content goes here. Remember to clear flag bits:
// TCON::IE1 (External Interrupt 1)
//
// Whenever a negative edge appears on P0.3, toggle LED_BLUE.
// The interrupt pending flag is automatically cleared by vectoring to the ISR
//
//-----------------------------------------------------------------------------
/*SI_INTERRUPT (INT1_ISR, INT1_IRQn)
{
	LED_BLUE = !LED_BLUE;
}*/

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
// Here we process the Timer0 interrupt and toggle the LED when appropriate
//
//-----------------------------------------------------------------------------
/*static uint16_t timer = 0;

SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
	static uint16_t counter = 0;

	counter++;

	if(counter == LED_TOGGLE_RATE)
	{
		LED_RED = !LED_RED;                    // Toggle the LED
		timer++;
		counter = 0;
	}
}*/

